"""empty message

Revision ID: 8626fba83e14
Revises: 
Create Date: 2024-01-30 18:04:16.178000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8626fba83e14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
                    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('login', sa.String(), server_default='unknown', nullable=True),
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('passwordHash', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('index'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('wallet_table',
                    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('userID', sa.UUID(), nullable=False),
                    sa.Column('address', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['userID'], ['user_table.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('index'),
                    sa.UniqueConstraint('address')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
